spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Flashes/config-repo
          username: Flashes
          password: zc970329
          basedir: D:\\ideaWork\\config\\basedir
  rabbitmq:
    host: 106.14.122.223
    port: 5672
    username: admin
    password: zc12138
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      expose: "*"
server:
  port: 8082